name: pytest

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    env:
      NOX_PYTHON_VERSIONS:  ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'requirements/*.txt'
    - name: update pip
      run: |
        pip install -U wheel
        pip install -U setuptools
        python -m pip install -U pip
    - run: pip install nox
    - run: nox
