name: pytest

on: [pull_request]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
    - name: Install dependencies
      run: |
        pip install --upgrade --upgrade-strategy eager pip setuptools wheel
        pip install --upgrade --upgrade-strategy eager -r requirements.txt
        pip install --upgrade --upgrade-strategy eager .
        pip install --upgrade --upgrade-strategy eager .[test,dev]
    - name: Check types with pytype
      run: |
        pytype -j "$(grep -c ^processor /proc/cpuinfo)" magi
    - name: Test with pytest
      run: |
        pytest -n "$(grep -c ^processor /proc/cpuinfo)" magi
